version: "2"
services:
  postgres:
    container_name: postgres-docker
    image: postgres:10
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=togepi
    ports:
    - 5432:5432
  app:
    build: .
    ports:
    - 8080:8080
    depends_on:
    - postgres
